/**
 * Generates a slug from a given input string.
 * The slug is generated by:
 * 1. Removing leading/trailing whitespace
 * 2. Converting to lowercase for consistency and readability
 * 3. Removing non-alphanumeric characters (except spaces, underscores, hyphens)
 * 4. Replacing sequences of spaces, underscores, or hyphens with a single hyphen
 * 5. Removing leading or trailing hyphens
 *
 * @param {string} input The input string to generate the slug from
 * @returns {string} The generated slug
 */
export const generateSlug = function (input: string): string {
  return input
    ?.trim() // 1. Remove leading/trailing whitespace
    .toLowerCase() // 2. Convert to lowercase for consistency and readability
    .replace(/[^\w\s-]/g, "") // 3. Remove non-alphanumeric characters (except spaces, underscores, hyphens)
    .replace(/[\s_-]+/g, "-") // 4. Replace sequences of spaces, underscores, or hyphens with a single hyphen
    .replace(/^-+|-+$/g, ""); // 5. Remove leading or trailing hyphens
};
